// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFG98AeQY79lcN_ldcLeFO8fTg8RoCZc0',
    appId: '1:227120203075:web:23cfef3eeb111e5d365bf6',
    messagingSenderId: '227120203075',
    projectId: 'womensafe-59c17',
    authDomain: 'womensafe-59c17.firebaseapp.com',
    storageBucket: 'womensafe-59c17.appspot.com',
    measurementId: 'G-ZNMK89P0MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuPX-BFkEKGxN6a_OIeZVXTE1FGSknMmg',
    appId: '1:227120203075:android:36ac3a9ed190a370365bf6',
    messagingSenderId: '227120203075',
    projectId: 'womensafe-59c17',
    storageBucket: 'womensafe-59c17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQo2twG3IlFytnYFl2BMjx6sXwgX1a6M4',
    appId: '1:227120203075:ios:6a4820b423ab1412365bf6',
    messagingSenderId: '227120203075',
    projectId: 'womensafe-59c17',
    storageBucket: 'womensafe-59c17.appspot.com',
    iosBundleId: 'com.techpro.womensafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQo2twG3IlFytnYFl2BMjx6sXwgX1a6M4',
    appId: '1:227120203075:ios:d48917c7e24645d9365bf6',
    messagingSenderId: '227120203075',
    projectId: 'womensafe-59c17',
    storageBucket: 'womensafe-59c17.appspot.com',
    iosBundleId: 'com.techpro.womensafe.RunnerTests',
  );
}
